
# install configuration

CFLAGS  ?= -g -Wall
CC      ?= cc
CC_PROG ?= "$(CC) ~src-file~ $(CFLAGS) -c -o ~exec-file~.o"
CC_EXEC ?= "$(CC) ~exec-file~.o ~obj-files~ -pthread -lcyclone -lck -lm $(CFLAGS) -o ~exec-file~"
CC_LIB  ?= "$(CC) ~src-file~ $(CFLAGS) -c -o ~exec-file~.o"

AR        ?= ar
#CD        ?= cd
RM        ?= rm -f
#LS        ?= ls
#CP        ?= cp
#LN        ?= ln
INSTALL   ?= install
MKDIR     ?= $(INSTALL) -d
RMDIR     ?= rmdir

PREFIX    ?= /usr/local
BINDIR    ?= $(PREFIX)/bin
LIBDIR    ?= $(PREFIX)/lib
INCDIR    ?= $(PREFIX)/include/cyclone
DATADIR   ?= $(PREFIX)/share/cyclone

DESTDIR   ?=
