# Cyclone Scheme
# Copyright (c) 2014, Justin Ethier
# All rights reserved.
#
# Configuration options for the makefile

# Platform-specific flags, set to 0 if not supported
CYC_PLATFORM_HAS_MEMSTREAM ?= 1

# Compiler options
CFLAGS       ?= -O2 -Wall -Iinclude -L.
COMP_CFLAGS  ?= -O2 -Wall -I$(PREFIX)/include -L$(PREFIX)/lib
# Use these lines instead for debugging or profiling
#CFLAGS = -g -Wall
#CFLAGS = -g -pg -Wall
CC      ?= cc
LIBS = -pthread -lcyclone -lck -lm

# Commands "baked into" cyclone for invoking the C compiler
CC_PROG ?= "$(CC) ~src-file~ $(COMP_CFLAGS) -c -o ~exec-file~.o"
CC_EXEC ?= "$(CC) ~exec-file~.o ~obj-files~ $(LIBS) $(COMP_CFLAGS) -o ~exec-file~"
CC_LIB  ?= "$(CC) ~src-file~ $(COMP_CFLAGS) -c -o ~exec-file~.o"

AR        ?= ar
#CD        ?= cd
RM        ?= rm -f
#LS        ?= ls
#CP        ?= cp
#LN        ?= ln
INSTALL   ?= install
MKDIR     ?= $(INSTALL) -d
RMDIR     ?= rmdir

PREFIX    ?= /usr/local
BINDIR    ?= $(PREFIX)/bin
LIBDIR    ?= $(PREFIX)/lib
INCDIR    ?= $(PREFIX)/include/cyclone
DATADIR   ?= $(PREFIX)/share/cyclone

DESTDIR   ?=
